import Image from 'next/image';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, Calendar, Check, ChevronDown, Clock, FileText, HeartPulse, LayoutDashboard, MapPin, Phone, Plus, Search, ShieldCheck, Star, Stethoscope, Users } from 'lucide-react';
import { articles, doctors, services, specialties } from '@/lib/data';
import { PageHero, SectionHead } from './SiteShell';

const Cta = () => <section className="mini-cta"><div><p className="eyebrow light">Cần hỗ trợ lựa chọn?</p><h2>Hãy để chúng tôi lắng nghe.</h2></div><Link className="button button-lime" href="/dat-lich">Đặt lịch tư vấn <ArrowUpRight/></Link></section>;

export function AboutPage() { return <><PageHero eyebrow="Câu chuyện Hoàng Khanh" title="Gần người bệnh hơn, mỗi ngày." copy="Từ một phòng khám chuyên khoa Nội đến một hệ thống chăm sóc đa chuyên khoa — chúng tôi lớn lên từ sự tin tưởng của cộng đồng Chư Sê."/><section className="about-statement container"><p>Chúng tôi tin rằng chất lượng y khoa không chỉ nằm ở thiết bị hay bằng cấp, mà còn ở cách một bác sĩ <em>lắng nghe, giải thích và đồng hành.</em></p></section><section className="about-image"><Image src="/images/clinic-interior.png" fill alt="Không gian Hoàng Khanh Medical"/></section><section className="section container split-copy"><div><p className="eyebrow">Từ 2016 đến hôm nay</p><h2>Một hành trình được xây bằng niềm tin.</h2></div><div className="timeline">{[['2016','Khởi đầu từ Phòng khám CK Nội Lê Văn Phúc.'],['2020','Mở rộng năng lực chẩn đoán và xét nghiệm.'],['2024','Nâng cấp không gian, quy trình và đội ngũ.'],['2026','Hoàng Khanh Medical — hệ sinh thái chăm sóc mới.']].map(x=><div key={x[0]} data-reveal><b>{x[0]}</b><p>{x[1]}</p></div>)}</div></section><section className="values"><div className="container"><SectionHead eyebrow="Điều chúng tôi theo đuổi" title="Chuyên môn. Minh bạch. Tận tâm."/><div className="value-grid">{[['01','An toàn','Mỗi quy trình đều bắt đầu bằng nguyên tắc an toàn người bệnh.'],['02','Chính trực','Tư vấn cần thiết, chi phí rõ ràng, thông tin dễ hiểu.'],['03','Đồng hành','Theo dõi sau khám để việc chăm sóc không dừng ở cửa phòng.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section><Cta/></> }

export function ListingPage({ type }:{type:'specialties'|'services'|'doctors'|'articles'}) {
  const config = {
    specialties: ['Hệ chuyên khoa','Chăm sóc đúng nơi, từ bước đầu.','Tìm hiểu từng chuyên khoa, triệu chứng thường gặp và đội ngũ phù hợp.'],
    services: ['Dịch vụ y tế','Rõ ràng trước khi bắt đầu.','Thông tin dịch vụ, quy trình và mức giá tham khảo được trình bày minh bạch.'],
    doctors: ['Đội ngũ bác sĩ','Chuyên môn tạo niềm tin.','Gặp gỡ đội ngũ bác sĩ tận tâm đang đồng hành cùng sức khỏe cộng đồng.'],
    articles: ['Kiến thức y khoa','Thông tin đúng để sống khỏe hơn.','Bài viết được biên soạn theo ngôn ngữ gần gũi, giúp bạn ra quyết định tốt hơn.'],
  }[type];
  const items = type==='specialties'?specialties:type==='services'?services:type==='doctors'?doctors:articles;
  return <><PageHero eyebrow={config[0]} title={config[1]} copy={config[2]}/><section className="section container"><div className={`listing-grid ${type}`}>
    {items.map((raw:any,i)=>{ const href = type==='specialties'?`/chuyen-khoa/${raw.slug}`:type==='services'?`/dich-vu/${raw.slug}`:type==='doctors'?`/bac-si/${raw.slug}`:`/tin-tuc/${raw.slug}`; return <Link href={href} className="listing-card" key={raw.slug} data-reveal>{type==='doctors'&&<div className={`avatar avatar-${i+1}`}>{raw.name.split(' ').slice(-2).map((x:string)=>x[0]).join('')}</div>}<span className="card-index">0{i+1}</span>{raw.icon&&<raw.icon size={30}/>}<small>{raw.eyebrow||raw.category||raw.specialty}</small><h3>{raw.name||raw.title}</h3><p>{raw.desc||raw.excerpt||raw.focus}</p><div className="card-foot"><b>{raw.price||raw.metric||raw.exp||raw.date}</b><i><ArrowUpRight/></i></div></Link>})}
  </div></section><Cta/></>;
}

export function DetailPage({ kind, slug }:{kind:'specialty'|'service'|'doctor'|'article';slug:string}) {
  const data:any = kind==='specialty'?specialties.find(x=>x.slug===slug):kind==='service'?services.find(x=>x.slug===slug):kind==='doctor'?doctors.find(x=>x.slug===slug):articles.find(x=>x.slug===slug);
  if(!data) return <PageHero eyebrow="Không tìm thấy" title="Nội dung đang được cập nhật." copy="Vui lòng quay lại trang danh mục."/>;
  if(kind==='article') return <ArticleDetail data={data}/>;
  const title=data.name; const eyebrow=kind==='doctor'?data.specialty:data.category||data.eyebrow; const copy=data.desc||data.bio||data.focus;
  return <><section className="detail-hero"><div className="container detail-grid"><div><Link href={kind==='specialty'?'/chuyen-khoa':kind==='service'?'/dich-vu':'/bac-si'} className="back-link"><ArrowLeft/> Quay lại</Link><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p><div className="detail-actions"><Link className="button button-dark" href="/dat-lich">Đặt lịch <ArrowUpRight/></Link><a className="text-link" href="tel:0914010104">Gọi 0914 010 104</a></div></div><div className="detail-visual">{kind==='doctor'?<Image src="/images/doctor-hero.png" fill alt={title}/>:<div className="detail-symbol">{data.icon&&<data.icon size={88}/>}<span>{data.metric||data.price}</span></div>}</div></div></section><section className="section container detail-content"><aside><span>Tổng quan</span><span>Quy trình</span><span>Chuẩn bị</span><span>Câu hỏi thường gặp</span></aside><article><p className="eyebrow">Tổng quan</p><h2>{kind==='doctor'?'Chăm sóc bằng chuyên môn và sự thấu cảm.':'Một hành trình rõ ràng, dễ hiểu.'}</h2><p>{kind==='doctor'?data.quote:'Mỗi dịch vụ tại Hoàng Khanh Medical được xây dựng quanh ba nguyên tắc: đánh giá đúng, giải thích rõ và theo dõi đủ. Bác sĩ sẽ trao đổi trực tiếp để bạn hiểu từng bước trước khi quyết định.'}</p><div className="info-block"><h3>Điều bạn có thể mong đợi</h3><ul><li><Check/>Tiếp nhận nhanh và tôn trọng quyền riêng tư</li><li><Check/>Tư vấn cá nhân hóa theo nhu cầu thực tế</li><li><Check/>Chi phí dự kiến được thông báo trước</li><li><Check/>Hướng dẫn theo dõi sau buổi khám</li></ul></div></article></section><Cta/></>;
}

function ArticleDetail({data}:{data:any}) { return <article className="article-detail"><header><Link href="/tin-tuc" className="back-link"><ArrowLeft/> Kiến thức y khoa</Link><p className="eyebrow">{data.category} · {data.date}</p><h1>{data.title}</h1><p>{data.excerpt}</p></header><div className="article-cover"><div className="article-wave"/><HeartPulse/></div><div className="article-body"><p className="lead">Chủ động hiểu các chỉ số sức khỏe giúp mỗi người nhận biết sớm thay đổi của cơ thể và tìm đến bác sĩ đúng lúc.</p><h2>Điều quan trọng cần ghi nhớ</h2><p>Thông tin y khoa chỉ thực sự hữu ích khi được đặt trong bối cảnh của từng người. Tuổi, tiền sử gia đình, lối sống và các bệnh đang điều trị đều ảnh hưởng đến đánh giá của bác sĩ.</p><blockquote>Đừng chờ cơ thể “lên tiếng thật lớn” mới bắt đầu quan tâm. Một cuộc kiểm tra đúng thời điểm có thể thay đổi cả hành trình sức khỏe.</blockquote><h2>Khi nào nên đi khám?</h2><p>Nếu triệu chứng kéo dài, tái phát hoặc ảnh hưởng sinh hoạt, bạn nên trao đổi với nhân viên y tế. Trường hợp khó thở, đau ngực, rối loạn ý thức hoặc yếu liệt đột ngột cần được cấp cứu ngay.</p><div className="medical-note"><ShieldCheck/><p><b>Lưu ý y khoa</b>Nội dung có tính chất tham khảo, không thay thế chẩn đoán và điều trị trực tiếp.</p></div></div></article> }

export function BookingPage() {
  const [step,setStep]=useState(1); const [specialty,setSpecialty]=useState('Nội tổng quát'); const [doctor,setDoctor]=useState('BS. CKI Lê Văn Phúc'); const [time,setTime]=useState('08:30');
  const steps=['Chuyên khoa','Bác sĩ','Ngày & giờ','Thông tin','Xác nhận'];
  return <section className="booking-page"><div className="booking-aside"><Link href="/" className="back-link light"><ArrowLeft/> Trang chủ</Link><div><p className="eyebrow light">Đặt lịch trực tuyến</p><h1>Chăm sóc bắt đầu từ một lựa chọn nhỏ.</h1><p>Khoảng 2 phút để hoàn tất. Thông tin của bạn được bảo mật.</p></div><div className="booking-help"><Phone/><span><small>Cần hỗ trợ?</small><b>0914 010 104</b></span></div></div><div className="booking-main"><div className="stepper">{steps.map((s,i)=><button key={s} className={step>=i+1?'active':''} onClick={()=>i+1<step&&setStep(i+1)}><span>{step>i+1?<Check/>:i+1}</span><small>{s}</small></button>)}</div><div className="booking-panel">
    {step===1&&<ChoiceStep title="Bạn cần khám chuyên khoa nào?" copy="Nếu chưa chắc chắn, hãy chọn Nội tổng quát để được tư vấn ban đầu.">{specialties.map(s=><Choice key={s.slug} active={specialty===s.name} onClick={()=>setSpecialty(s.name)} icon={<s.icon/>} title={s.name} copy={s.desc}/>)}</ChoiceStep>}
    {step===2&&<ChoiceStep title="Chọn bác sĩ đồng hành" copy={`Các bác sĩ phù hợp với ${specialty}.`}>{doctors.map(d=><Choice key={d.slug} active={doctor===d.name} onClick={()=>setDoctor(d.name)} icon={<div className="mini-avatar">{d.name.split(' ').pop()?.[0]}</div>} title={d.name} copy={`${d.specialty} · ${d.exp}`}/>)}</ChoiceStep>}
    {step===3&&<div><StepTitle title="Chọn ngày và giờ" copy="Các khung giờ trống được cập nhật theo lịch bác sĩ."/><div className="date-row">{['25 Thg 9','26 Thg 9','27 Thg 9','28 Thg 9'].map((d,i)=><button className={i===1?'active':''} key={d}><small>{['Thứ Sáu','Thứ Bảy','Chủ Nhật','Thứ Hai'][i]}</small><b>{d}</b></button>)}</div><h3 className="slot-title">Buổi sáng</h3><div className="time-grid">{['07:30','08:00','08:30','09:30','10:00','10:30'].map(t=><button key={t} className={time===t?'active':''} onClick={()=>setTime(t)}>{t}</button>)}</div></div>}
    {step===4&&<div><StepTitle title="Thông tin người bệnh" copy="Vui lòng nhập đúng thông tin để phòng khám liên hệ xác nhận."/><div className="form-grid"><label>Họ và tên<input placeholder="Nguyễn Văn A"/></label><label>Số điện thoại<input type="tel" placeholder="0901 234 567"/></label><label>Ngày sinh<input type="date"/></label><label>Giới tính<select><option>Nam</option><option>Nữ</option><option>Khác</option></select></label><label className="full">Lý do khám<textarea placeholder="Mô tả ngắn triệu chứng hoặc nhu cầu của bạn"/></label></div></div>}
    {step===5&&<div className="confirm"><div className="confirm-icon"><Check/></div><StepTitle title="Kiểm tra lại lịch hẹn" copy="Lịch chỉ được ghi nhận sau khi bạn nhấn xác nhận."/><div className="summary"><div><span>Chuyên khoa</span><b>{specialty}</b></div><div><span>Bác sĩ</span><b>{doctor}</b></div><div><span>Thời gian</span><b>Thứ Bảy, 26/09 · {time}</b></div><div><span>Địa điểm</span><b>621 Hùng Vương, Chư Sê</b></div></div></div>}
    <div className="booking-controls">{step>1?<button className="button button-ghost" onClick={()=>setStep(step-1)}>Quay lại</button>:<span/>}<button className="button button-dark" onClick={()=>step<5&&setStep(step+1)}>{step===5?'Xác nhận lịch hẹn':'Tiếp tục'} <ArrowRight/></button></div>
  </div></div></section>;
}
const StepTitle=({title,copy}:{title:string;copy:string})=><div className="step-title"><p className="eyebrow">Bước tiếp theo</p><h2>{title}</h2><p>{copy}</p></div>;
const ChoiceStep=({title,copy,children}:{title:string;copy:string;children:React.ReactNode})=><div><StepTitle title={title} copy={copy}/><div className="choice-grid">{children}</div></div>;
const Choice=({active,onClick,icon,title,copy}:{active:boolean;onClick:()=>void;icon:React.ReactNode;title:string;copy:string})=><button className={`choice ${active?'active':''}`} onClick={onClick}><span className="choice-icon">{icon}</span><span><b>{title}</b><small>{copy}</small></span><i>{active&&<Check/>}</i></button>;

export function ContactPage({faq=false}:{faq?:boolean}) { const questions=['Tôi có cần đặt lịch trước không?','Phòng khám có làm việc cuối tuần?','Tôi cần chuẩn bị gì trước khi xét nghiệm?','Kết quả được trả bằng hình thức nào?']; return <><PageHero eyebrow={faq?'Trợ giúp':'Kết nối cùng Hoàng Khanh'} title={faq?'Những câu hỏi thường gặp.':'Chúng tôi luôn sẵn sàng lắng nghe.'} copy="Gọi trực tiếp nếu bạn cần hỗ trợ khẩn hoặc để lại lời nhắn cho những câu hỏi khác."/><section className="section container contact-grid"><div className="contact-info"><div><Phone/><span><small>Hotline</small><a href="tel:0914010104">0914 010 104</a></span></div><div><MapPin/><span><small>Địa chỉ</small><b>621 Hùng Vương, Chư Sê, Gia Lai</b></span></div><div><Clock/><span><small>Giờ làm việc</small><b>Hằng ngày, 07:00–19:00</b></span></div></div>{faq?<div className="faq-list">{questions.map(q=><details key={q}><summary>{q}<ChevronDown/></summary><p>Nhân viên Hoàng Khanh sẽ hướng dẫn cụ thể theo dịch vụ và tình trạng của bạn. Bạn có thể gọi hotline để được tư vấn nhanh nhất.</p></details>)}</div>:<form className="contact-form" onSubmit={e=>e.preventDefault()}><h2>Gửi lời nhắn</h2><label>Họ và tên<input placeholder="Tên của bạn"/></label><label>Số điện thoại<input placeholder="0901 234 567"/></label><label>Nội dung<textarea placeholder="Chúng tôi có thể giúp gì cho bạn?"/></label><button className="button button-dark">Gửi tin nhắn <ArrowUpRight/></button></form>}</section></> }

export function SearchPage() { const [q,setQ]=useState(''); const all=useMemo(()=>[...specialties.map(x=>({name:x.name,type:'Chuyên khoa',href:`/chuyen-khoa/${x.slug}`})),...doctors.map(x=>({name:x.name,type:'Bác sĩ',href:`/bac-si/${x.slug}`})),...services.map(x=>({name:x.name,type:'Dịch vụ',href:`/dich-vu/${x.slug}`})),...articles.map(x=>({name:x.title,type:'Bài viết',href:`/tin-tuc/${x.slug}`}))].filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[q]); return <section className="search-page container"><p className="eyebrow">Tìm kiếm toàn trang</p><h1>Bạn đang tìm điều gì?</h1><div className="search-box"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Bác sĩ, chuyên khoa, dịch vụ..."/></div><div className="search-results">{q?all.map(x=><Link href={x.href} key={x.href}><span>{x.type}</span><b>{x.name}</b><ArrowUpRight/></Link>):<p>Gợi ý: “Tim mạch”, “Nhi khoa”, “xét nghiệm”</p>}</div></section> }

export function PatientPage({mode}:{mode:'portal'|'login'|'register'|'appointments'}) { if(mode==='login'||mode==='register') return <section className="auth-page"><div className="auth-visual"><Image src="/images/clinic-interior.png" fill alt="Hoàng Khanh Medical"/></div><form onSubmit={e=>e.preventDefault()}><Link href="/" className="back-link"><ArrowLeft/> Trang chủ</Link><p className="eyebrow">Cổng bệnh nhân</p><h1>{mode==='login'?'Chào mừng trở lại.':'Tạo tài khoản của bạn.'}</h1>{mode==='register'&&<label>Họ và tên<input placeholder="Nguyễn Văn A"/></label>}<label>Số điện thoại hoặc email<input placeholder="name@example.com"/></label><label>Mật khẩu<input type="password" placeholder="••••••••"/></label><button className="button button-dark">{mode==='login'?'Đăng nhập':'Đăng ký'} <ArrowRight/></button><p>{mode==='login'?'Chưa có tài khoản? ':'Đã có tài khoản? '}<Link href={mode==='login'?'/dang-ky':'/dang-nhap'}>{mode==='login'?'Đăng ký':'Đăng nhập'}</Link></p></form></section>; return <><PageHero eyebrow="Cổng bệnh nhân" title={mode==='appointments'?'Lịch hẹn của bạn.':'Sức khỏe của bạn, trong một nơi.'} copy="Quản lý lịch khám, xem hướng dẫn chuẩn bị và theo dõi thông tin chăm sóc."/><section className="section container patient-cards">{[['Lịch sắp tới','26.09 · 08:30','BS. CKI Lê Văn Phúc'],['Kết quả gần nhất','Xét nghiệm tổng quát','18.09.2026'],['Hồ sơ sức khỏe','Thông tin của bạn','Được bảo mật']].map((x,i)=><article key={x[0]}><span>{i===0?<Calendar/>:i===1?<FileText/>:<ShieldCheck/>}</span><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p><button>Xem chi tiết <ArrowRight/></button></article>)}</section></> }

export function AdminPage({section='Tổng quan'}:{section?:string}) { const menu=['Tổng quan','Bác sĩ','Chuyên khoa','Dịch vụ','Lịch khám','Bài viết','Bệnh nhân','Nội dung']; const href=(x:string)=>x==='Tổng quan'?'/admin':`/admin/${{'Bác sĩ':'bac-si','Chuyên khoa':'chuyen-khoa','Dịch vụ':'dich-vu','Lịch khám':'lich-kham','Bài viết':'bai-viet','Bệnh nhân':'benh-nhan','Nội dung':'noi-dung'}[x]}`; return <section className="admin-shell"><aside><Link href="/" className="admin-logo"><Activity/>HK <span>Medical</span></Link><nav>{menu.map(x=><Link href={href(x)} className={section===x?'active':''} key={x}>{x==='Tổng quan'?<LayoutDashboard/>:x==='Bệnh nhân'?<Users/>:<FileText/>}{x}</Link>)}</nav><Link href="/" className="back-site"><ArrowLeft/> Về website</Link></aside><main><header><div><p>Quản trị hệ thống</p><h1>{section}</h1></div><button className="button button-dark"><Plus/> Thêm mới</button></header><div className="admin-stats">{[['Lịch hôm nay','24','+12%'],['Bệnh nhân','1.248','+8%'],['Bác sĩ hoạt động','06','Ổn định'],['Dịch vụ','20','Đã cập nhật']].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><div className="admin-panel"><div className="admin-panel-head"><div><h2>{section==='Tổng quan'?'Lịch khám gần nhất':`Quản lý ${section.toLowerCase()}`}</h2><p>Dữ liệu minh họa cho giao diện quản trị.</p></div><div className="admin-search"><Search/><input placeholder="Tìm kiếm..."/></div></div><div className="data-table"><div className="data-head"><span>Mã / Tên</span><span>Loại</span><span>Trạng thái</span><span>Cập nhật</span></div>{['HK-09261','HK-09262','HK-09263','HK-09264','HK-09265'].map((x,i)=><div className="data-row" key={x}><span><b>{x}</b><small>{doctors[i%doctors.length].name}</small></span><span>{specialties[i%specialties.length].name}</span><span><i/> Đã xác nhận</span><span>Hôm nay · {8+i}:30</span></div>)}</div></div></main></section> }
