import Image from 'next/image';
import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, Calendar, Check, ChevronDown, Clock, FileText, HeartPulse, LayoutDashboard, MapPin, Phone, Search, ShieldCheck, Users } from 'lucide-react';
import { articles, doctors, services, specialties, type Article, type Doctor, type Service, type Specialty } from '@/lib/data';
import { PageHero, SectionHead } from './SiteShell';

const Cta = () => <section className="mini-cta"><div><p className="eyebrow light">Cần hỗ trợ lựa chọn?</p><h2>Hãy để chúng tôi lắng nghe.</h2></div><Link className="button button-lime" href="/dat-lich">Đặt lịch tư vấn <ArrowUpRight/></Link></section>;

export function AboutPage() { return <><PageHero eyebrow="Câu chuyện Hoàng Khanh" title="Gần người bệnh hơn, mỗi ngày." copy="Một định hướng chăm sóc chuyên khoa tại Chư Sê, được xây trên sự rõ ràng, tôn trọng và an toàn."/><section className="about-statement container"><p>Chất lượng y khoa không chỉ nằm ở thiết bị hay bằng cấp, mà còn ở cách một bác sĩ <em>lắng nghe, giải thích và đồng hành.</em></p></section><section className="about-image" data-image-reveal><Image src="/images/clinic-interior.png" fill alt="Không gian Hoàng Khanh Medical" sizes="100vw"/></section><section className="section container split-copy"><div><p className="eyebrow">Dấu mốc phát triển</p><h2>Một hành trình cần được kể bằng dữ liệu đã xác minh.</h2></div><div className="timeline">{[['Khởi đầu','Phòng khám chuyên khoa Nội Lê Văn Phúc — theo thông tin website cũ.'],['Mở rộng','Bổ sung năng lực chuyên khoa và xét nghiệm — mốc thời gian cần xác minh.'],['Hiện tại','Hoàng Khanh Medical tại Chư Sê, Gia Lai.']].map(x=><div key={x[0]} data-reveal><b>{x[0]}</b><p>{x[1]}</p></div>)}</div></section><section className="values"><div className="container"><SectionHead eyebrow="Điều chúng tôi theo đuổi" title="Chuyên môn. Minh bạch. Tận tâm."/><div className="value-grid">{[['01','An toàn','Mỗi quy trình cần bắt đầu bằng nguyên tắc an toàn người bệnh.'],['02','Chính trực','Chỉ công bố thông tin, giá và năng lực đã được đơn vị vận hành xác minh.'],['03','Đồng hành','Hướng dẫn rõ bước tiếp theo sau mỗi lần tiếp nhận.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section><section className="section container content-model"><p className="eyebrow">An toàn phòng xét nghiệm</p><h2>BSL-2 là gì?</h2><p className="page-intro">BSL-2 là cấp độ an toàn sinh học dành cho hoạt động với tác nhân có nguy cơ ở mức vừa phải, yêu cầu kiểm soát tiếp cận, thực hành phòng xét nghiệm phù hợp, phương tiện bảo hộ và quy trình xử lý sự cố.</p><div className="service-facts"><div><small>Kiểm soát</small><b>Giới hạn tiếp cận khu vực làm việc</b></div><div><small>Thực hành</small><b>Giảm tạo khí dung và phơi nhiễm</b></div><div><small>Bảo vệ</small><b>PPE, khử nhiễm và quản lý chất thải</b></div></div><div className="draft-banner"><ShieldCheck/><p><b>Phạm vi công bố</b>Website cũ giới thiệu phòng xét nghiệm BSL-2; giấy phép, hồ sơ thẩm định, danh mục xét nghiệm và thiết bị vẫn cần phòng khám cung cấp để công bố chính xác.</p></div></section><Cta/></> }

export function ListingPage({ type }:{type:'specialties'|'services'|'doctors'|'articles'}) {
  const config = {
    specialties: ['Hệ chuyên khoa','Chăm sóc đúng nơi, từ bước đầu.','Tìm hiểu từng chuyên khoa, triệu chứng thường gặp và đội ngũ phù hợp.'],
    services: ['Dịch vụ y tế','Rõ ràng trước khi bắt đầu.','Thông tin dịch vụ, quy trình và mức giá tham khảo được trình bày minh bạch.'],
    doctors: ['Đội ngũ bác sĩ','Chuyên môn tạo niềm tin.','Gặp gỡ đội ngũ bác sĩ tận tâm đang đồng hành cùng sức khỏe cộng đồng.'],
    articles: ['Kiến thức y khoa','Thông tin đúng để sống khỏe hơn.','Bài viết được biên soạn theo ngôn ngữ gần gũi, giúp bạn ra quyết định tốt hơn.'],
  }[type];
  return <><PageHero eyebrow={config[0]} title={config[1]} copy={config[2]}/><section className="section container"><div className={`listing-grid ${type}`}>
    {type==='specialties'&&specialties.map((item,i)=><Link href={`/chuyen-khoa/${item.slug}`} className="listing-card" key={item.slug} data-reveal><span className="card-index">0{i+1}</span><item.icon size={30}/><small>{item.eyebrow}</small><h3>{item.name}</h3><p>{item.desc}</p><div className="card-foot"><b>{item.metric}</b><i><ArrowUpRight/></i></div></Link>)}
    {type==='services'&&services.map((item,i)=><Link href={`/dich-vu/${item.slug}`} className="listing-card" key={item.slug} data-reveal><span className="card-index">0{i+1}</span><item.icon size={30}/><small>{item.category}</small><h3>{item.name}</h3><p>{item.desc}</p><div className="card-foot"><b>{item.price}</b><i><ArrowUpRight/></i></div></Link>)}
    {type==='doctors'&&doctors.map((item,i)=><Link href={`/bac-si/${item.slug}`} className="listing-card" key={item.slug} data-reveal><div className={`avatar avatar-${i+1}`}>{item.name.split(' ').slice(-2).map(x=>x[0]).join('')}</div><span className="card-index">0{i+1}</span><small>{item.specialty}</small><h3>{item.name}</h3><p>{item.focus}</p><div className="card-foot"><b>{item.verified?'Đã xác minh':'Hồ sơ chờ xác minh'}</b><i><ArrowUpRight/></i></div></Link>)}
    {type==='articles'&&articles.map((item,i)=><Link href={`/tin-tuc/${item.slug}`} className="listing-card" key={item.slug} data-reveal><span className="card-index">0{i+1}</span><small>{item.category}</small><h3>{item.title}</h3><p>{item.excerpt}</p><div className="card-foot"><b>{item.date}</b><i><ArrowUpRight/></i></div></Link>)}
  </div></section><Cta/></>;
}

export function DetailPage({ kind, slug }:{kind:'specialty'|'service'|'doctor'|'article';slug:string}) {
  if(kind==='article'){const item=articles.find(x=>x.slug===slug);return item?<ArticleDetail data={item}/>:null}
  if(kind==='specialty'){const item=specialties.find(x=>x.slug===slug);return item?<SpecialtyDetail data={item}/>:null}
  if(kind==='service'){const item=services.find(x=>x.slug===slug);return item?<ServiceDetail data={item}/>:null}
  const item=doctors.find(x=>x.slug===slug);return item?<DoctorDetail data={item}/>:null;
}

const InfoList=({title,items}:{title:string;items:string[]})=><section className="content-block" data-reveal><h2>{title}</h2>{items.length?<ul>{items.map(item=><li key={item}><Check/>{item}</li>)}</ul>:<p className="pending-copy">Thông tin đang chờ phòng khám xác minh và bổ sung.</p>}</section>;
const DetailHero=({title,eyebrow,copy,back,visual,cta}:{title:string;eyebrow:string;copy:string;back:string;visual:React.ReactNode;cta:string})=><section className="detail-hero"><div className="container detail-grid"><div><Link href={back} className="back-link"><ArrowLeft/> Quay lại</Link><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p><div className="detail-actions"><Link className="button button-dark" href="/dat-lich">{cta} <ArrowUpRight/></Link><a className="text-link" href="tel:0914010104">Gọi 0914 010 104</a></div></div><div className="detail-visual">{visual}</div></div></section>;

function SpecialtyDetail({data}:{data:Specialty}){return <><DetailHero title={data.name} eyebrow={data.eyebrow} copy={data.desc} back="/chuyen-khoa" cta={`Đặt lịch khám ${data.name}`} visual={<div className="detail-symbol"><data.icon size={88}/><span>{data.metric}</span></div>}/><section className="section container content-model"><InfoList title="Các vấn đề thường được đánh giá" items={data.conditions}/><InfoList title="Triệu chứng nên đi khám" items={data.symptoms}/><InfoList title="Ai nên khám?" items={data.audiences}/><InfoList title="Phương pháp chẩn đoán" items={data.diagnostics}/><InfoList title="Kỹ thuật và trang thiết bị" items={data.technology}/><InfoList title="Quy trình khám" items={data.process}/><FaqBlock items={data.faq}/></section><Cta/></>}
function ServiceDetail({data}:{data:Service}){return <><DetailHero title={data.name} eyebrow={data.category} copy={data.desc} back="/dich-vu" cta="Đặt lịch dịch vụ này" visual={<div className="detail-symbol"><data.icon size={88}/><span>{data.price}</span></div>}/><section className="section container content-model"><div className="service-facts"><div><small>Giá</small><b>{data.price}</b></div><div><small>Thời gian</small><b>{data.duration}</b></div><div><small>Chuyên khoa</small><b>{data.specialty}</b></div></div><InfoList title="Đối tượng phù hợp" items={data.suitableFor}/><InfoList title="Chỉ định" items={data.indications}/><InfoList title="Chống chỉ định / lưu ý" items={data.contraindications}/><InfoList title="Chuẩn bị trước khi thực hiện" items={data.preparation}/><InfoList title="Quy trình" items={data.process}/><section className="content-block"><h2>Kết quả</h2><p>{data.result}</p></section><FaqBlock items={data.faq}/></section><Cta/></>}
function DoctorDetail({data}:{data:Doctor}){return <><DetailHero title={data.name} eyebrow={data.specialty} copy={data.focus} back="/bac-si" cta={`Đặt lịch với ${data.name}`} visual={<Image src="/images/doctor-hero.png" fill alt={`Ảnh đại diện tạm thời của ${data.name}`}/>}/><section className="section container content-model">{!data.verified&&<div className="draft-banner"><ShieldCheck/><p><b>Hồ sơ chưa được xác minh</b>Học vị và thông tin tên được tham chiếu từ website cũ; phòng khám cần đối chiếu hồ sơ trước khi công bố.</p></div>}<div className="service-facts"><div><small>Học vị</small><b>{data.degree}</b></div><div><small>Chức danh</small><b>{data.role}</b></div><div><small>Lịch khám</small><b>{data.schedule}</b></div></div><InfoList title="Lĩnh vực chuyên môn" items={data.expertise}/><InfoList title="Học vấn" items={data.education}/><InfoList title="Chứng chỉ" items={data.certifications}/><InfoList title="Quá trình công tác" items={data.career}/><InfoList title="Thế mạnh điều trị" items={data.strengths}/><InfoList title="Dịch vụ thực hiện" items={data.services}/></section><Cta/></>}
const FaqBlock=({items}:{items:Array<[string,string]>})=><section className="content-block faq-list"><h2>Câu hỏi thường gặp</h2>{items.map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</section>;
function ArticleDetail({data}:{data:Article}) { return <article className="article-detail"><header><Link href="/tin-tuc" className="back-link"><ArrowLeft/> Kiến thức y khoa</Link><p className="eyebrow">{data.category} · {data.date}</p><h1>{data.title}</h1><p>{data.excerpt}</p><div className="article-byline"><span>Tác giả: {data.author}</span><span>Duyệt y khoa: {data.reviewer}</span><span>Cập nhật: {data.updatedAt}</span></div></header><div className="article-cover"><div className="article-wave"/><HeartPulse/></div><div className="article-body"><nav className="toc" aria-label="Mục lục"><b>Trong bài viết</b>{data.headings.map((item,index)=><a key={item.title} href={`#section-${index}`}>{item.title}</a>)}</nav>{data.headings.map((item,index)=><section id={`section-${index}`} key={item.title}><h2>{item.title}</h2><p>{item.body}</p></section>)}<h2>Tài liệu tham khảo</h2><ul>{data.references.map(reference=><li key={reference}>{reference}</li>)}</ul><div className="medical-note"><ShieldCheck/><p><b>Lưu ý y khoa</b>Nội dung có tính chất tham khảo, không thay thế chẩn đoán và điều trị trực tiếp. Bản nháp cần được người duyệt y khoa xác nhận trước khi công bố.</p></div><Link className="button button-dark" href="/dat-lich">Trao đổi với bác sĩ <ArrowUpRight/></Link></div></article> }

export function BookingPage() {
  const [step,setStep]=useState(1);
  const [specialty,setSpecialty]=useState(specialties[0].slug);
  const [doctor,setDoctor]=useState(doctors[0].slug);
  const [date,setDate]=useState('');
  const [slots,setSlots]=useState<Array<{id:string;startsAt:string;endsAt:string}>>([]);
  const [slotId,setSlotId]=useState('');
  const [reason,setReason]=useState('');
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const [success,setSuccess]=useState<{code:string;doctor:string;startsAt:string}|null>(null);
  const selectedSpecialty=specialties.find(s=>s.slug===specialty) ?? specialties[0];
  const selectedDoctor=doctors.find(d=>d.slug===doctor) ?? doctors[0];
  const dates=useMemo(()=>Array.from({length:7},(_,index)=>{const day=new Date();day.setDate(day.getDate()+index+1);return {value:day.toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}),label:day.toLocaleDateString('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})}}),[]);
  useEffect(()=>{ if(step!==3||!date)return; const controller=new AbortController(); setLoading(true);setError('');setSlotId('');fetch(`/api/slots?doctor=${encodeURIComponent(doctor)}&date=${date}`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setSlots(body.slots)}).catch(err=>{if(err.name!=='AbortError')setError(err.message||'Không thể tải lịch trống.')}).finally(()=>setLoading(false));return()=>controller.abort()},[date,doctor,step]);
  const steps=['Chuyên khoa','Bác sĩ','Ngày & giờ','Thông tin','Xác nhận'];
  async function createAppointment(){setLoading(true);setError('');try{const response=await fetch('/api/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slotId,doctorSlug:doctor,reason})});const body=await response.json();if(!response.ok)throw new Error(body.error);setSuccess(body.appointment)}catch(err){setError(err instanceof Error?err.message:'Không thể tạo lịch hẹn.')}finally{setLoading(false)}}
  if(success)return <section className="booking-success"><div className="confirm-icon"><Check/></div><p className="eyebrow">Đặt lịch thành công</p><h1>Mã lịch hẹn {success.code}</h1><p>{success.doctor} · {new Date(success.startsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p><Link href="/lich-hen" className="button button-dark">Quản lý lịch hẹn <ArrowRight/></Link></section>;
  return <section className="booking-page"><div className="booking-aside"><Link href="/" className="back-link light"><ArrowLeft/> Trang chủ</Link><div><p className="eyebrow light">Đặt lịch trực tuyến</p><h1>Chăm sóc bắt đầu từ một lựa chọn nhỏ.</h1><p>Khoảng 2 phút để hoàn tất. Thông tin của bạn được bảo mật.</p></div><div className="booking-help"><Phone/><span><small>Cần hỗ trợ?</small><b>0914 010 104</b></span></div></div><div className="booking-main"><div className="stepper">{steps.map((s,i)=><button key={s} className={step>=i+1?'active':''} onClick={()=>i+1<step&&setStep(i+1)}><span>{step>i+1?<Check/>:i+1}</span><small>{s}</small></button>)}</div><div className="booking-panel">
    {step===1&&<ChoiceStep title="Bạn cần khám chuyên khoa nào?" copy="Nếu chưa chắc chắn, hãy chọn Nội tổng quát để được tư vấn ban đầu.">{specialties.map(s=><Choice key={s.slug} active={specialty===s.slug} onClick={()=>setSpecialty(s.slug)} icon={<s.icon/>} title={s.name} copy={s.desc}/>)}</ChoiceStep>}
    {step===2&&<ChoiceStep title="Chọn bác sĩ đồng hành" copy={`Danh sách hồ sơ đang có cho ${selectedSpecialty.name}.`}>{doctors.map(d=><Choice key={d.slug} active={doctor===d.slug} onClick={()=>setDoctor(d.slug)} icon={<div className="mini-avatar">{d.name.split(' ').pop()?.[0]}</div>} title={d.name} copy={`${d.specialty} · Hồ sơ cần phòng khám xác minh`}/>)}</ChoiceStep>}
    {step===3&&<div><StepTitle title="Chọn ngày và giờ" copy="Chỉ các khung giờ còn trống trong hệ thống được hiển thị."/><div className="date-row">{dates.slice(0,4).map(d=><button className={date===d.value?'active':''} onClick={()=>setDate(d.value)} key={d.value}><b>{d.label}</b></button>)}</div><h3 className="slot-title">Khung giờ khả dụng</h3>{loading?<p role="status">Đang tải lịch trống…</p>:slots.length?<div className="time-grid">{slots.map(slot=><button key={slot.id} className={slotId===slot.id?'active':''} onClick={()=>setSlotId(slot.id)}>{new Date(slot.startsAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})}</button>)}</div>:<p className="empty-state">{date?'Chưa có khung giờ trống cho ngày này.':'Chọn ngày để xem lịch trống.'}</p>}</div>}
    {step===4&&<div><StepTitle title="Thông tin buổi khám" copy="Thông tin tài khoản bệnh nhân được lấy từ phiên đăng nhập và không hiển thị công khai."/><div className="form-grid"><label className="full">Lý do khám (không bắt buộc)<textarea value={reason} onChange={event=>setReason(event.target.value)} maxLength={1000} placeholder="Mô tả ngắn triệu chứng hoặc nhu cầu của bạn"/></label></div><p className="privacy-hint"><ShieldCheck/> Dữ liệu này chỉ được gửi khi bạn xác nhận lịch hẹn.</p></div>}
    {step===5&&<div className="confirm"><div className="confirm-icon"><Check/></div><StepTitle title="Kiểm tra lại lịch hẹn" copy="Hệ thống sẽ khóa khung giờ bằng transaction khi bạn xác nhận."/><div className="summary"><div><span>Chuyên khoa</span><b>{selectedSpecialty.name}</b></div><div><span>Bác sĩ</span><b>{selectedDoctor.name}</b></div><div><span>Thời gian</span><b>{slots.find(slot=>slot.id===slotId)?new Date(slots.find(slot=>slot.id===slotId)!.startsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa chọn'}</b></div><div><span>Địa điểm</span><b>621 Hùng Vương, Chư Sê</b></div></div></div>}
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="booking-controls">{step>1?<button className="button button-ghost" onClick={()=>setStep(step-1)}>Quay lại</button>:<span/>}<button className="button button-dark" disabled={loading||(step===3&&!slotId)} onClick={()=>step<5?setStep(step+1):createAppointment()}>{loading?'Đang xử lý…':step===5?'Xác nhận lịch hẹn':'Tiếp tục'} <ArrowRight/></button></div>
  </div></div></section>;
}
const StepTitle=({title,copy}:{title:string;copy:string})=><div className="step-title"><p className="eyebrow">Bước tiếp theo</p><h2>{title}</h2><p>{copy}</p></div>;
const ChoiceStep=({title,copy,children}:{title:string;copy:string;children:React.ReactNode})=><div><StepTitle title={title} copy={copy}/><div className="choice-grid">{children}</div></div>;
const Choice=({active,onClick,icon,title,copy}:{active:boolean;onClick:()=>void;icon:React.ReactNode;title:string;copy:string})=><button className={`choice ${active?'active':''}`} onClick={onClick}><span className="choice-icon">{icon}</span><span><b>{title}</b><small>{copy}</small></span><i>{active&&<Check/>}</i></button>;

const faqItems = [
  ['Đặt lịch','Tôi có cần đặt lịch trước không?','Bạn có thể đến trực tiếp hoặc đặt lịch trước. Đặt lịch giúp phòng khám chuẩn bị tốt hơn và giảm thời gian chờ; thời gian tiếp nhận thực tế có thể thay đổi theo tình trạng chuyên môn.'],
  ['Giờ làm việc','Phòng khám có làm việc cuối tuần?','Website hiện niêm yết thời gian tiếp nhận hằng ngày 07:00–19:00. Vui lòng gọi hotline để xác nhận lịch làm việc vào ngày lễ.'],
  ['Xét nghiệm','Tôi cần chuẩn bị gì trước khi xét nghiệm?','Việc cần nhịn ăn hoặc chuẩn bị khác phụ thuộc loại xét nghiệm. Không tự ngừng thuốc; hãy xác nhận với nhân viên y tế trước ngày thực hiện.'],
  ['Kết quả','Kết quả được trả bằng hình thức nào?','Hình thức và thời gian trả kết quả phụ thuộc dịch vụ. Nhân viên tiếp nhận sẽ thông báo cụ thể khi bạn đăng ký.'],
];

export function ContactPage({faq=false}:{faq?:boolean}) {
  const [state,setState]=useState<'idle'|'loading'|'success'|'error'>('idle');
  const [message,setMessage]=useState('');
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState('loading');setMessage('');const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,privacyConsent:form.get('privacyConsent')==='on'})});const body=await response.json();if(!response.ok)throw new Error(body.error);setState('success');event.currentTarget.reset()}catch(error){setState('error');setMessage(error instanceof Error?error.message:'Không thể gửi lời nhắn.')}}
  return <><PageHero eyebrow={faq?'Trợ giúp':'Kết nối cùng Hoàng Khanh'} title={faq?'Những câu hỏi thường gặp.':'Chúng tôi luôn sẵn sàng lắng nghe.'} copy="Gọi trực tiếp nếu bạn cần hỗ trợ khẩn hoặc để lại lời nhắn cho những câu hỏi khác."/><section className="section container contact-grid"><div className="contact-info"><div><Phone/><span><small>Hotline</small><a href="tel:0914010104">0914 010 104</a></span></div><div><MapPin/><span><small>Địa chỉ</small><b>621 Hùng Vương, Chư Sê, Gia Lai</b></span></div><div><Clock/><span><small>Giờ làm việc</small><b>Hằng ngày, 07:00–19:00</b></span></div></div>{faq?<div className="faq-list">{faqItems.map(([category,question,answer])=><details key={question}><summary><span><small>{category}</small>{question}</span><ChevronDown/></summary><p>{answer}</p></details>)}</div>:<form className="contact-form" onSubmit={submit} noValidate><h2>Gửi lời nhắn</h2><label>Họ và tên<input name="fullName" required minLength={2} autoComplete="name"/></label><label>Số điện thoại<input name="phone" type="tel" required autoComplete="tel"/></label><label>Email (không bắt buộc)<input name="email" type="email" autoComplete="email"/></label><label>Chủ đề<select name="topic" required defaultValue=""><option value="" disabled>Chọn chủ đề</option><option>Đặt lịch</option><option>Dịch vụ</option><option>Kết quả</option><option>Góp ý</option></select></label><label>Nội dung<textarea name="message" required minLength={10}/></label><label className="consent"><input type="checkbox" name="privacyConsent" required/> Tôi đồng ý để phòng khám sử dụng thông tin này nhằm phản hồi yêu cầu.</label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/>{state==='success'&&<p className="form-success" role="status">Đã nhận lời nhắn. Phòng khám sẽ phản hồi theo thông tin bạn cung cấp.</p>}{state==='error'&&<p className="form-error" role="alert">{message}</p>}<button disabled={state==='loading'} className="button button-dark">{state==='loading'?'Đang gửi…':'Gửi tin nhắn'} <ArrowUpRight/></button></form>}</section></>;
}

export function SearchPage() { const [q,setQ]=useState(''); const all=useMemo(()=>[...specialties.map(x=>({name:x.name,type:'Chuyên khoa',href:`/chuyen-khoa/${x.slug}`})),...doctors.map(x=>({name:x.name,type:'Bác sĩ',href:`/bac-si/${x.slug}`})),...services.map(x=>({name:x.name,type:'Dịch vụ',href:`/dich-vu/${x.slug}`})),...articles.map(x=>({name:x.title,type:'Bài viết',href:`/tin-tuc/${x.slug}`}))].filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[q]); return <section className="search-page container"><p className="eyebrow">Tìm kiếm toàn trang</p><h1>Bạn đang tìm điều gì?</h1><div className="search-box"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Bác sĩ, chuyên khoa, dịch vụ..."/></div><div className="search-results">{q?all.map(x=><Link href={x.href} key={x.href}><span>{x.type}</span><b>{x.name}</b><ArrowUpRight/></Link>):<p>Gợi ý: “Tim mạch”, “Nhi khoa”, “xét nghiệm”</p>}</div></section> }

type PortalAppointment={id:string;code:string;status:string;doctor:{name:string;slug:string};service:{name:string}|null;slot:{startsAt:string;endsAt:string};preparation:string|null};
export function PatientPage({mode}:{mode:'portal'|'login'|'register'|'appointments'}) {
  const [appointments,setAppointments]=useState<PortalAppointment[]>([]);const [loading,setLoading]=useState(mode==='portal'||mode==='appointments');const [error,setError]=useState('');
  useEffect(()=>{if(mode==='login'||mode==='register')return;fetch('/api/appointments').then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setAppointments(body.appointments)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[mode]);
  async function authenticate(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch(`/api/auth/${mode==='login'?'login':'register'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const body=await response.json();if(!response.ok)throw new Error(body.error);const next=new URLSearchParams(window.location.search).get('next');window.location.assign(next&&next.startsWith('/')?next:'/benh-nhan')}catch(reason){setError(reason instanceof Error?reason.message:'Không thể đăng nhập.');setLoading(false)}}
  async function cancel(id:string){if(!window.confirm('Bạn muốn hủy lịch hẹn này?'))return;const response=await fetch(`/api/appointments/${id}`,{method:'DELETE'});if(response.ok)setAppointments(items=>items.map(item=>item.id===id?{...item,status:'CANCELLED'}:item));else{const body=await response.json();setError(body.error)}}
  if(mode==='login'||mode==='register') return <section className="auth-page"><div className="auth-visual"><Image src="/images/clinic-interior.png" fill alt="Không gian Hoàng Khanh Medical"/></div><form onSubmit={authenticate}><Link href="/" className="back-link"><ArrowLeft/> Trang chủ</Link><p className="eyebrow">Cổng bệnh nhân</p><h1>{mode==='login'?'Chào mừng trở lại.':'Tạo tài khoản của bạn.'}</h1>{mode==='register'&&<><label>Họ và tên<input name="name" required autoComplete="name"/></label><label>Số điện thoại<input name="phone" type="tel" required autoComplete="tel"/></label><label>Email (không bắt buộc)<input name="email" type="email" autoComplete="email"/></label></>} {mode==='login'&&<label>Số điện thoại hoặc email<input name="identity" required autoComplete="username"/></label>}<label>Mật khẩu<input name="password" type="password" required minLength={10} autoComplete={mode==='login'?'current-password':'new-password'}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button disabled={loading} className="button button-dark">{loading?'Đang xử lý…':mode==='login'?'Đăng nhập':'Đăng ký'} <ArrowRight/></button><p>{mode==='login'?'Chưa có tài khoản? ':'Đã có tài khoản? '}<Link href={mode==='login'?'/dang-ky':'/dang-nhap'}>{mode==='login'?'Đăng ký':'Đăng nhập'}</Link></p></form></section>;
  const now=Date.now();const visible=mode==='appointments'?appointments:appointments.filter(item=>new Date(item.slot.startsAt).getTime()>=now).slice(0,2);
  return <><PageHero eyebrow="Cổng bệnh nhân" title={mode==='appointments'?'Lịch hẹn của bạn.':'Sức khỏe của bạn, trong một nơi.'} copy="Dữ liệu trên trang này chỉ được tải sau khi xác thực phiên đăng nhập."/><section className="section container">{loading?<p role="status">Đang tải lịch hẹn…</p>:error?<div className="error-state" role="alert">{error}</div>:visible.length?<div className="appointment-list">{visible.map(item=><article key={item.id}><div><small>{item.code} · {item.status}</small><h3>{item.doctor.name}</h3><p>{new Date(item.slot.startsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}{item.service?` · ${item.service.name}`:''}</p>{item.preparation&&<p>{item.preparation}</p>}</div>{['PENDING','CONFIRMED'].includes(item.status)&&<button onClick={()=>cancel(item.id)} className="button button-ghost">Hủy lịch</button>}</article>)}</div>:<div className="empty-state"><Calendar/><h2>Chưa có lịch hẹn</h2><p>Khi bạn đặt lịch, thông tin sẽ xuất hiện tại đây.</p><Link href="/dat-lich" className="button button-dark">Đặt lịch khám</Link></div>}</section></>;
}

export function LegalPage({type}:{type:'privacy'|'terms'|'booking'}) {
  const content={privacy:{eyebrow:'Quyền riêng tư',title:'Chính sách bảo mật — bản dự thảo',intro:'Tài liệu này mô tả cấu trúc xử lý dữ liệu dự kiến và cần được đơn vị vận hành cùng cố vấn pháp lý rà soát trước khi công bố chính thức.',sections:[['Dữ liệu được thu thập','Thông tin liên hệ, tài khoản và lịch hẹn chỉ nên được thu thập khi cần để tiếp nhận, xác thực và cung cấp dịch vụ.'],['Mục đích sử dụng','Dữ liệu không nên được dùng ngoài mục đích người dùng đã được thông báo nếu chưa có căn cứ hoặc đồng ý phù hợp.'],['Lưu trữ và quyền của bạn','Thời hạn lưu trữ, đầu mối yêu cầu truy cập, chỉnh sửa hoặc xóa dữ liệu cần được phòng khám xác nhận.']]},terms:{eyebrow:'Điều khoản',title:'Điều khoản sử dụng — bản dự thảo',intro:'Nội dung website nhằm cung cấp thông tin chung và không thay thế việc khám, chẩn đoán hoặc xử trí cấp cứu.',sections:[['Phạm vi thông tin','Thông tin y khoa trên website mang tính tham khảo. Người dùng cần trao đổi trực tiếp với nhân viên y tế khi có triệu chứng hoặc câu hỏi điều trị.'],['Tài khoản','Người dùng có trách nhiệm bảo vệ thông tin đăng nhập và cung cấp thông tin chính xác khi đặt lịch.'],['Rà soát pháp lý','Các giới hạn trách nhiệm và cơ chế giải quyết khiếu nại phải được luật sư rà soát trước khi ban hành.']]},booking:{eyebrow:'Đặt lịch',title:'Chính sách đặt lịch — bản dự thảo',intro:'Các điều kiện dưới đây là khung vận hành đề xuất, chưa phải cam kết chính thức của phòng khám.',sections:[['Xác nhận lịch','Một lịch hẹn chỉ có hiệu lực khi hệ thống tạo mã và hiển thị trạng thái xác nhận phù hợp.'],['Thay đổi hoặc hủy','Website đề xuất tự hủy trước 24 giờ; quy định thực tế, phí và ngoại lệ cần được phòng khám xác nhận.'],['Tình huống khẩn cấp','Đặt lịch trực tuyến không dành cho cấp cứu. Khi có dấu hiệu nguy hiểm, hãy liên hệ cơ sở cấp cứu phù hợp.']]}}[type];
  return <><PageHero eyebrow={content.eyebrow} title={content.title} copy={content.intro}/><section className="section container legal-page"><div className="draft-banner"><ShieldCheck/><p><b>Cần rà soát trước khi phát hành</b>Không xem nội dung này là tư vấn pháp lý hoặc chính sách đã được phê duyệt.</p></div>{content.sections.map(([title,body])=><article key={title}><h2>{title}</h2><p>{body}</p></article>)}</section></>;
}

type AdminOverview={todayCount:number;upcomingCount:number;doctorCount:number;contacts:Array<{id:string;fullName:string;topic:string;createdAt:string}>};
export function AdminPage({section='Tổng quan'}:{section?:string}) {
  const [overview,setOverview]=useState<AdminOverview|null>(null);const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/admin/overview').then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setOverview(body)}).catch(reason=>setError(reason.message))},[]);
  const menu=['Tổng quan','Bác sĩ','Chuyên khoa','Dịch vụ','Lịch khám','Bài viết','Bệnh nhân','Nội dung'];
  const href=(x:string)=>x==='Tổng quan'?'/admin':`/admin/${{'Bác sĩ':'bac-si','Chuyên khoa':'chuyen-khoa','Dịch vụ':'dich-vu','Lịch khám':'lich-kham','Bài viết':'bai-viet','Bệnh nhân':'benh-nhan','Nội dung':'noi-dung'}[x as Exclude<typeof menu[number],'Tổng quan'>]}`;
  return <section className="admin-shell"><aside><Link href="/" className="admin-logo"><Activity/>HK <span>Medical</span></Link><nav>{menu.map(x=><Link href={href(x)} className={section===x?'active':''} key={x}>{x==='Tổng quan'?<LayoutDashboard/>:x==='Bệnh nhân'?<Users/>:<FileText/>}{x}</Link>)}</nav><Link href="/" className="back-site"><ArrowLeft/> Về website</Link></aside><main><header><div><p>Quản trị hệ thống</p><h1>{section}</h1></div></header>{error?<div className="error-state" role="alert">{error}</div>:<><div className="admin-stats">{[['Lịch hôm nay',overview?.todayCount],['Lịch sắp tới',overview?.upcomingCount],['Bác sĩ công khai',overview?.doctorCount],['Liên hệ mới',overview?.contacts.length]].map(([label,value])=><article key={label}><small>{label}</small><b>{value??'—'}</b><span>Dữ liệu trực tiếp</span></article>)}</div><div className="admin-panel"><div className="admin-panel-head"><div><h2>Liên hệ mới nhất</h2><p>Không hiển thị dữ liệu bệnh nhân trong bảng tổng quan công khai.</p></div></div><div className="data-table"><div className="data-head"><span>Người gửi</span><span>Chủ đề</span><span>Trạng thái</span><span>Thời gian</span></div>{overview?.contacts.length?overview.contacts.map(item=><div className="data-row" key={item.id}><span><b>{item.fullName}</b></span><span>{item.topic}</span><span><i/> Mới</span><span>{new Date(item.createdAt).toLocaleString('vi-VN')}</span></div>):<p className="empty-state">Chưa có liên hệ mới.</p>}</div></div></>}</main></section>;
}
