import { Baby, Bone, Ear, HeartPulse, Microscope, Scan, Stethoscope, Venus, type LucideIcon } from 'lucide-react';

export type Specialty = {
  slug:string; name:string; eyebrow:string; icon:LucideIcon; desc:string; metric:string;
  conditions:string[]; symptoms:string[]; audiences:string[]; diagnostics:string[]; technology:string[]; process:string[]; faq:Array<[string,string]>;
};
export type Doctor = {
  slug:string; name:string; specialty:string; exp:string; focus:string; quote:string; verified:boolean;
  degree:string; role:string; expertise:string[]; education:string[]; certifications:string[]; career:string[]; strengths:string[]; services:string[]; schedule:string;
};
export type Service = {
  slug:string; name:string; category:string; price:string; icon:LucideIcon; desc:string;
  suitableFor:string[]; indications:string[]; contraindications:string[]; preparation:string[]; process:string[]; duration:string; result:string; specialty:string; faq:Array<[string,string]>;
};
export type Article = {
  slug:string; category:string; date:string; updatedAt:string; title:string; excerpt:string; author:string; reviewer:string;
  headings:Array<{title:string;body:string}>; references:string[]; draft:boolean;
};

export const specialties:Specialty[] = [
  {slug:'noi-tong-quat',name:'Nội tổng quát',eyebrow:'Chăm sóc toàn diện',icon:Stethoscope,desc:'Thăm khám ban đầu, đánh giá triệu chứng và quản lý sức khỏe lâu dài cho người trưởng thành.',metric:'Đánh giá tổng quát',conditions:['Tăng huyết áp và rối loạn chuyển hóa','Bệnh hô hấp thường gặp','Rối loạn tiêu hóa','Theo dõi bệnh mạn tính'],symptoms:['Mệt mỏi kéo dài hoặc sụt cân chưa rõ nguyên nhân','Sốt, ho hoặc khó chịu tái diễn','Đau bụng, rối loạn tiêu hóa','Cần đánh giá sức khỏe ban đầu'],audiences:['Người trưởng thành cần khám triệu chứng mới','Người có bệnh nền cần theo dõi định kỳ','Người chưa biết nên bắt đầu từ chuyên khoa nào'],diagnostics:['Khai thác bệnh sử và khám lâm sàng','Đo dấu hiệu sinh tồn','Chỉ định xét nghiệm hoặc chẩn đoán hình ảnh khi cần'],technology:['Thiết bị theo dõi dấu hiệu sinh tồn','Hệ thống lưu trữ kết quả — cần xác minh triển khai'],process:['Tiếp nhận và ghi nhận lý do khám','Khám, đánh giá nguy cơ','Tư vấn chỉ định phù hợp','Hướng dẫn theo dõi hoặc chuyển chuyên khoa'],faq:[['Có cần nhịn ăn trước khi khám?','Khám nội tổng quát không phải lúc nào cũng cần nhịn ăn. Nếu có xét nghiệm, nhân viên sẽ hướng dẫn theo từng chỉ định.'],['Khi nào cần đi cấp cứu?','Đau ngực dữ dội, khó thở, rối loạn ý thức hoặc yếu liệt đột ngột cần được đánh giá cấp cứu, không chờ lịch khám.']]},
  {slug:'nhi-khoa',name:'Nhi khoa',eyebrow:'Đồng hành cùng trẻ',icon:Baby,desc:'Đánh giá các vấn đề sức khỏe thường gặp ở trẻ trong môi trường thân thiện với gia đình.',metric:'Trẻ em & thiếu niên',conditions:['Nhiễm khuẩn hô hấp thường gặp','Rối loạn tiêu hóa ở trẻ','Theo dõi tăng trưởng và dinh dưỡng','Tư vấn chăm sóc trẻ'],symptoms:['Sốt hoặc ho kéo dài','Ăn uống kém, nôn hoặc tiêu chảy','Chậm tăng cân','Trẻ quấy khóc bất thường'],audiences:['Trẻ sơ sinh, trẻ nhỏ và thiếu niên','Phụ huynh cần tư vấn chăm sóc và dinh dưỡng'],diagnostics:['Khám lâm sàng theo lứa tuổi','Đánh giá biểu đồ tăng trưởng','Xét nghiệm theo chỉ định bác sĩ'],technology:['Dụng cụ khám phù hợp trẻ em','Không gian khám thân thiện — cần xác minh thực tế'],process:['Tiếp nhận thông tin từ người chăm sóc','Khám và đánh giá dấu hiệu cảnh báo','Tư vấn điều trị/chăm sóc','Hẹn theo dõi khi cần'],faq:[['Có nên tự dùng thuốc hạ sốt?','Cần dùng đúng loại và liều theo cân nặng, theo hướng dẫn nhân viên y tế. Không tự phối hợp nhiều thuốc có cùng hoạt chất.'],['Khi nào cần đưa trẻ đi cấp cứu?','Khó thở, tím tái, co giật, li bì hoặc mất nước rõ là những dấu hiệu cần hỗ trợ y tế khẩn.']]},
  {slug:'san-phu-khoa',name:'Sản phụ khoa',eyebrow:'Chăm sóc riêng tư',icon:Venus,desc:'Tư vấn sức khỏe phụ nữ, theo dõi thai kỳ và thăm khám trong không gian tôn trọng riêng tư.',metric:'Sức khỏe phụ nữ',conditions:['Rối loạn kinh nguyệt','Theo dõi thai kỳ','Tư vấn sức khỏe sinh sản','Các triệu chứng phụ khoa thường gặp'],symptoms:['Đau bụng dưới hoặc ra huyết bất thường','Rối loạn chu kỳ','Khí hư bất thường','Cần theo dõi thai kỳ'],audiences:['Phụ nữ cần khám định kỳ hoặc có triệu chứng','Thai phụ cần tư vấn lịch theo dõi'],diagnostics:['Khám lâm sàng theo chỉ định','Siêu âm khi phù hợp','Xét nghiệm theo đánh giá của bác sĩ'],technology:['Siêu âm — cấu hình thiết bị cần phòng khám xác minh','Không gian tư vấn riêng tư'],process:['Trao đổi riêng tư về nhu cầu khám','Khám và chỉ định phù hợp','Giải thích kết quả','Lập kế hoạch theo dõi'],faq:[['Có cần chuẩn bị trước khi siêu âm?','Cách chuẩn bị phụ thuộc loại siêu âm và tuổi thai. Hãy xác nhận với nhân viên khi đặt lịch.'],['Có thể đi cùng người thân không?','Việc người thân cùng tham gia tùy mong muốn của người bệnh và quy định tại khu vực khám.']]},
  {slug:'tim-mach',name:'Tim mạch',eyebrow:'Theo dõi nguy cơ',icon:HeartPulse,desc:'Sàng lọc yếu tố nguy cơ và theo dõi các vấn đề tim mạch theo chỉ định chuyên môn.',metric:'Theo dõi dài hạn',conditions:['Tăng huyết áp','Rối loạn nhịp cần đánh giá','Nguy cơ tim mạch','Theo dõi bệnh tim đã chẩn đoán'],symptoms:['Đau ngực hoặc khó thở khi gắng sức','Hồi hộp, đánh trống ngực','Phù chân','Huyết áp bất thường'],audiences:['Người có yếu tố nguy cơ tim mạch','Người cần theo dõi huyết áp hoặc bệnh mạn'],diagnostics:['Khám tim mạch','Điện tâm đồ theo chỉ định','Siêu âm tim hoặc xét nghiệm khi cần'],technology:['Điện tâm đồ — cần xác minh model thiết bị','Siêu âm tim — cần xác minh năng lực thực tế'],process:['Đánh giá triệu chứng và nguy cơ','Khám và đo chỉ số','Chỉ định cận lâm sàng phù hợp','Tư vấn kế hoạch theo dõi'],faq:[['Đau ngực có thể chờ đặt lịch không?','Đau ngực dữ dội, kéo dài, kèm khó thở hoặc vã mồ hôi cần được đánh giá cấp cứu ngay.'],['Có cần mang kết quả cũ?','Nên mang theo đơn thuốc, điện tim, siêu âm và xét nghiệm trước đây nếu có.']]},
  {slug:'tai-mui-hong',name:'Tai mũi họng',eyebrow:'Đánh giá triệu chứng',icon:Ear,desc:'Thăm khám các triệu chứng tai, mũi và họng ở trẻ em và người lớn.',metric:'Tai · Mũi · Họng',conditions:['Viêm mũi xoang','Viêm họng và amidan','Rối loạn tai thường gặp','Khàn tiếng kéo dài'],symptoms:['Đau tai hoặc giảm thính lực','Nghẹt mũi kéo dài','Đau họng tái diễn','Khàn tiếng'],audiences:['Trẻ em và người lớn có triệu chứng tai mũi họng'],diagnostics:['Khám tai mũi họng','Nội soi khi có chỉ định','Xét nghiệm hoặc hình ảnh học khi cần'],technology:['Hệ thống nội soi — thông số cần xác minh'],process:['Ghi nhận triệu chứng','Khám lâm sàng','Nội soi nếu cần và có đồng ý','Tư vấn điều trị/theo dõi'],faq:[['Nội soi có đau không?','Mức khó chịu tùy từng người và kỹ thuật. Nhân viên y tế sẽ giải thích trước khi thực hiện.'],['Khàn tiếng bao lâu thì nên khám?','Khàn tiếng kéo dài hoặc kèm khó thở, nuốt đau cần được nhân viên y tế đánh giá.']]},
  {slug:'chan-doan-hinh-anh',name:'Chẩn đoán hình ảnh',eyebrow:'Hỗ trợ chẩn đoán',icon:Scan,desc:'Thực hiện kỹ thuật hình ảnh theo chỉ định để hỗ trợ bác sĩ đánh giá tình trạng sức khỏe.',metric:'Theo chỉ định',conditions:['Đánh giá ổ bụng','Theo dõi thai kỳ','Đánh giá tim mạch','Khảo sát mô mềm theo chỉ định'],symptoms:['Có chỉ định từ bác sĩ','Cần theo dõi tình trạng đã biết'],audiences:['Người có chỉ định chẩn đoán hình ảnh phù hợp'],diagnostics:['Đối chiếu chỉ định','Thực hiện kỹ thuật phù hợp','Bác sĩ đọc và trả kết quả'],technology:['Thiết bị siêu âm — model và năng lực cần xác minh'],process:['Kiểm tra chỉ định và chuẩn bị','Giải thích quy trình','Thực hiện kỹ thuật','Trả kết quả và hướng dẫn bước tiếp theo'],faq:[['Có cần nhịn ăn không?','Một số khảo sát ổ bụng có thể yêu cầu nhịn ăn hoặc nhịn tiểu. Hãy xác nhận theo đúng loại kỹ thuật.'],['Kết quả có thay thế khám bác sĩ không?','Không. Kết quả hình ảnh cần được diễn giải cùng triệu chứng, khám lâm sàng và các dữ liệu liên quan.']]},
];

// TODO(content): phòng khám phải xác minh từng hồ sơ trước khi đặt verified=true.
export const doctors:Doctor[] = [
  {slug:'le-van-phuc',name:'BS. CKI Lê Văn Phúc',specialty:'Nội tổng quát',exp:'Kinh nghiệm cần xác minh',focus:'Nội tổng quát',quote:'Hồ sơ chuyên môn đang chờ phòng khám xác minh.',verified:false,degree:'BS. CKI — theo website cũ, cần đối chiếu hồ sơ',role:'Người sáng lập — theo website cũ',expertise:['Nội tổng quát'],education:[],certifications:[],career:[],strengths:[],services:['Khám nội tổng quát'],schedule:'Xem lịch trống trong hệ thống đặt lịch'},
  {slug:'nguyen-van-minh',name:'BS. CKII Nguyễn Văn Minh',specialty:'Nội tổng quát',exp:'Kinh nghiệm cần xác minh',focus:'Thông tin chuyên môn đang cập nhật',quote:'Hồ sơ chuyên môn đang chờ phòng khám xác minh.',verified:false,degree:'BS. CKII — theo website cũ, cần đối chiếu hồ sơ',role:'Bác sĩ',expertise:[],education:[],certifications:[],career:[],strengths:[],services:[],schedule:'Xem lịch trống trong hệ thống đặt lịch'},
  {slug:'tran-thi-hong',name:'BS. CKI Trần Thị Hồng',specialty:'Nhi khoa',exp:'Kinh nghiệm cần xác minh',focus:'Thông tin chuyên môn đang cập nhật',quote:'Hồ sơ chuyên môn đang chờ phòng khám xác minh.',verified:false,degree:'BS. CKI — theo website cũ, cần đối chiếu hồ sơ',role:'Bác sĩ',expertise:[],education:[],certifications:[],career:[],strengths:[],services:[],schedule:'Xem lịch trống trong hệ thống đặt lịch'},
  {slug:'le-hoang-nam',name:'BS. CKII Lê Hoàng Nam',specialty:'Sản phụ khoa',exp:'Kinh nghiệm cần xác minh',focus:'Thông tin chuyên môn đang cập nhật',quote:'Hồ sơ chuyên môn đang chờ phòng khám xác minh.',verified:false,degree:'BS. CKII — theo website cũ, cần đối chiếu hồ sơ',role:'Bác sĩ',expertise:[],education:[],certifications:[],career:[],strengths:[],services:[],schedule:'Xem lịch trống trong hệ thống đặt lịch'},
  {slug:'dang-anh-tuan',name:'ThS. BS Đặng Anh Tuấn',specialty:'Tim mạch',exp:'Kinh nghiệm cần xác minh',focus:'Thông tin chuyên môn đang cập nhật',quote:'Hồ sơ chuyên môn đang chờ phòng khám xác minh.',verified:false,degree:'ThS. BS — theo website cũ, cần đối chiếu hồ sơ',role:'Bác sĩ',expertise:[],education:[],certifications:[],career:[],strengths:[],services:[],schedule:'Xem lịch trống trong hệ thống đặt lịch'},
];

export const services:Service[] = [
  {slug:'kham-noi-tong-quat',name:'Khám nội tổng quát',category:'Khám lâm sàng',price:'Liên hệ để xác nhận giá',icon:Stethoscope,desc:'Đánh giá sức khỏe ban đầu và lập hướng theo dõi theo tình trạng cá nhân.',suitableFor:['Người trưởng thành có triệu chứng chưa rõ nguyên nhân','Người cần theo dõi bệnh mạn'],indications:['Đánh giá triệu chứng mới','Khám định kỳ theo tư vấn'],contraindications:[],preparation:['Mang theo đơn thuốc và kết quả cũ','Ghi lại triệu chứng và thời điểm xuất hiện'],process:['Tiếp nhận','Khám lâm sàng','Tư vấn chỉ định','Hướng dẫn theo dõi'],duration:'Thời lượng phụ thuộc tình trạng thực tế',result:'Nhận định ban đầu và kế hoạch tiếp theo',specialty:'Nội tổng quát',faq:[['Có bao gồm xét nghiệm không?','Xét nghiệm chỉ được thực hiện khi có chỉ định hoặc lựa chọn phù hợp; vui lòng xác nhận chi phí trước khi thực hiện.']]},
  {slug:'goi-tam-soat-tim-mach',name:'Đánh giá nguy cơ tim mạch',category:'Gói chăm sóc',price:'Giá cần phòng khám xác nhận',icon:HeartPulse,desc:'Khám và chỉ định phù hợp nhằm đánh giá các yếu tố nguy cơ tim mạch.',suitableFor:['Người có tăng huyết áp, đái tháo đường hoặc tiền sử gia đình'],indications:['Theo đánh giá bác sĩ'],contraindications:[],preparation:['Mang danh sách thuốc đang dùng','Không tự ngừng thuốc'],process:['Đánh giá nguy cơ','Khám','Chỉ định cận lâm sàng','Tư vấn'],duration:'Tùy danh mục chỉ định',result:'Báo cáo và kế hoạch theo dõi theo chỉ định',specialty:'Tim mạch',faq:[['Gói gồm những gì?','Danh mục cần được phòng khám xác nhận tại thời điểm đặt lịch; website không mặc định mọi người đều cần cùng một xét nghiệm.']]},
  {slug:'sieu-am-thai-4d',name:'Siêu âm thai',category:'Chẩn đoán hình ảnh',price:'Giá cần phòng khám xác nhận',icon:Scan,desc:'Theo dõi thai theo chỉ định; loại kỹ thuật và thời điểm thực hiện do nhân viên y tế tư vấn.',suitableFor:['Thai phụ có chỉ định phù hợp'],indications:['Theo lịch quản lý thai hoặc chỉ định bác sĩ'],contraindications:[],preparation:['Xác nhận cách chuẩn bị theo tuổi thai và loại siêu âm'],process:['Đối chiếu thông tin','Thực hiện kỹ thuật','Đọc kết quả','Tư vấn bước tiếp theo'],duration:'Theo loại khảo sát',result:'Kết quả hình ảnh và nhận xét chuyên môn',specialty:'Sản phụ khoa',faq:[['Siêu âm 4D có cần ở mọi lần khám?','Không nhất thiết. Loại siêu âm phù hợp phụ thuộc tuổi thai và mục tiêu chuyên môn.']]},
  {slug:'xet-nghiem-tong-quat',name:'Xét nghiệm tổng quát',category:'Xét nghiệm',price:'Giá theo danh mục chỉ định',icon:Microscope,desc:'Lấy mẫu và thực hiện danh mục xét nghiệm phù hợp với nhu cầu hoặc chỉ định.',suitableFor:['Người có chỉ định xét nghiệm','Người được tư vấn kiểm tra định kỳ'],indications:['Theo đánh giá của bác sĩ hoặc danh mục đã xác nhận'],contraindications:[],preparation:['Xác nhận yêu cầu nhịn ăn','Thông báo thuốc đang dùng'],process:['Xác nhận danh mục','Lấy mẫu','Phân tích','Trả kết quả'],duration:'Thời gian trả kết quả tùy danh mục',result:'Phiếu kết quả cần được diễn giải trong bối cảnh lâm sàng',specialty:'Nội tổng quát',faq:[['Xét nghiệm nào cần nhịn ăn?','Không phải mọi xét nghiệm đều yêu cầu nhịn ăn. Hãy xác nhận theo danh mục cụ thể.']]},
  {slug:'kham-co-xuong-khop',name:'Khám cơ xương khớp',category:'Khám chuyên khoa',price:'Giá cần phòng khám xác nhận',icon:Bone,desc:'Đánh giá đau và hạn chế vận động để định hướng xử trí phù hợp.',suitableFor:['Người đau khớp, đau lưng hoặc hạn chế vận động'],indications:['Đau kéo dài, tái diễn hoặc ảnh hưởng sinh hoạt'],contraindications:[],preparation:['Mang kết quả hình ảnh và đơn thuốc cũ nếu có'],process:['Hỏi bệnh','Khám vận động','Chỉ định khi cần','Kế hoạch theo dõi'],duration:'Phụ thuộc tình trạng',result:'Nhận định lâm sàng và hướng xử trí',specialty:'Nội tổng quát',faq:[['Có cần chụp phim trước không?','Không nên tự thực hiện hình ảnh học trước khi được đánh giá, trừ khi đã có chỉ định.']]},
];

export const articles:Article[] = [
  {slug:'hieu-dung-ve-tang-huyet-ap',category:'Tim mạch',date:'Bản nháp',updatedAt:'Chưa công bố',title:'Hiểu đúng về tăng huyết áp',excerpt:'Các khái niệm nền tảng, yếu tố nguy cơ và thời điểm cần trao đổi với nhân viên y tế.',author:'Ban biên tập — cần xác minh',reviewer:'Chưa chỉ định',draft:true,headings:[{title:'Vì sao cần theo dõi huyết áp?',body:'Huyết áp cần được đánh giá qua nhiều lần đo đúng kỹ thuật và trong bối cảnh sức khỏe của từng người.'},{title:'Khi nào cần hỗ trợ khẩn?',body:'Triệu chứng nặng như đau ngực, khó thở, rối loạn ý thức hoặc yếu liệt đột ngột cần được đánh giá cấp cứu.'}],references:['TODO: bổ sung hướng dẫn chuyên môn được người duyệt y khoa chấp thuận.']},
  {slug:'cham-soc-tre-khi-giao-mua',category:'Nhi khoa',date:'Bản nháp',updatedAt:'Chưa công bố',title:'Chăm sóc trẻ khi thời tiết thay đổi',excerpt:'Một khung theo dõi thực tế cho giấc ngủ, dinh dưỡng và các dấu hiệu cảnh báo.',author:'Ban biên tập — cần xác minh',reviewer:'Chưa chỉ định',draft:true,headings:[{title:'Theo dõi tổng trạng',body:'Khả năng ăn uống, hoạt động, nhịp thở và mức tỉnh táo thường hữu ích hơn việc chỉ nhìn vào một triệu chứng riêng lẻ.'},{title:'Dấu hiệu cần chú ý',body:'Khó thở, tím tái, co giật, li bì hoặc dấu hiệu mất nước cần được hỗ trợ y tế sớm.'}],references:['TODO: bổ sung tài liệu tham khảo được duyệt.']},
  {slug:'kham-suc-khoe-dinh-ky',category:'Y học dự phòng',date:'Bản nháp',updatedAt:'Chưa công bố',title:'Khám sức khỏe định kỳ nên bắt đầu từ đâu?',excerpt:'Cách chuẩn bị thông tin để buổi khám tập trung vào nguy cơ và nhu cầu thực tế.',author:'Ban biên tập — cần xác minh',reviewer:'Chưa chỉ định',draft:true,headings:[{title:'Không có một gói phù hợp cho mọi người',body:'Tuổi, tiền sử gia đình, lối sống và bệnh đang điều trị ảnh hưởng đến nội dung cần đánh giá.'},{title:'Chuẩn bị trước buổi khám',body:'Mang theo danh sách thuốc, kết quả cũ và ghi lại câu hỏi giúp trao đổi hiệu quả hơn.'}],references:['TODO: bổ sung khuyến cáo sàng lọc phù hợp tại Việt Nam.']},
];

export const nav = [['Giới thiệu','/gioi-thieu'],['Chuyên khoa','/chuyen-khoa'],['Dịch vụ','/dich-vu'],['Bác sĩ','/bac-si'],['Kiến thức','/tin-tuc'],['Liên hệ','/lien-he']] as const;

export const routePaths = [
  '', 'gioi-thieu', 'chuyen-khoa', ...specialties.map(x=>`chuyen-khoa/${x.slug}`),
  'dich-vu', ...services.map(x=>`dich-vu/${x.slug}`),
  'bac-si', ...doctors.map(x=>`bac-si/${x.slug}`), 'dat-lich',
  'tin-tuc', ...articles.map(x=>`tin-tuc/${x.slug}`), 'tim-kiem', 'lien-he', 'faq',
  'benh-nhan', 'dang-nhap', 'dang-ky', 'lich-hen', 'admin', 'admin/bac-si',
  'admin/chuyen-khoa', 'admin/dich-vu', 'admin/lich-kham', 'admin/bai-viet',
  'admin/benh-nhan', 'admin/noi-dung', 'chinh-sach-bao-mat', 'dieu-khoan-su-dung', 'chinh-sach-dat-lich'
];
